version: '3.7'

# Here we have to services means want to run two cotainer  app and postgres 

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - my-netwok
    # volumes:
    #   - .:/app
    # environment:
    #   - name=value

  postgres:
    image: postgres:latest
    environment:
       POSTGRES_USER: jp
       POSTGRES_PASSWORD: 1234
       POSTGRES_DB: Spring-POSTGRES_DB
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - postgres-s-data:/var/lib/postgresql/data

  networks:
    my-network:
      driver: bridge
  
  volumes:
    postgres-s-data:

    


